apiVersion: v1
kind: Secret
metadata:
  name: ${name}
  namespace: ${namespace}
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: ${repository}
  type: git
  insecure: "true"
  insecureIgnoreHostKey: "true"
data:
  sshPrivateKey: ${ssh_private_key_b64}
