apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: private-repo-creds
  namespace: ${namespace}
spec:
  refreshInterval: 1h
  target:
    name: argocd-external-secret
    creationPolicy: Owner
  secretStoreRef:
    name: secretstore-ssm
    kind: ClusterSecretStore
  data:
  - secretKey: ssh_private_key
    remoteRef:
      key: ${git_ssh_private_key}
