apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: secretstore-ssm
  namespace: ${namespace}
spec:
  provider:
    aws:
      service: ParameterStore
      region: ${aws_region}
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
