apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${name}
  namespace: ${namespace}
spec:
  project: ${project}
  source:
    repoURL: ${repo_url}
    path: ${path}
    targetRevision: ${rev}
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}
