apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ${hpa_name}
  namespace: ${namespace}
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${deploy_name}
  targetCPUUtilizationPercentage: 50
